<a href="https://colab.research.google.com/github/pranjalthakur25/Deep-Learning/blob/main/Backpropagation_Regression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1, activation='linear', input_dim=2))

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.get_weights()

[array([[-1.110959  , -0.14589381],
        [-0.5706717 , -0.03259325]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.89686525],
        [1.004309  ]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights=[np.array([[0.1,0.1],
                       [0.1,0.1]],dtype=np.float32),
                      np.array([0. ,0.],dtype=np.float32),
             np.array([[0.1],
                       [0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [23]:
model.set_weights(new_weights)

In [24]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [25]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 27.8902
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5774
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2604
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.8979
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5809
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 26.1811
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8513
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4597
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0508
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6597
Epoch 11/75
4/4 [==============================] - 0s 2ms/step - loss: 24.2660
Epoch 12/75
4/4 [==============================] - 0s 2ms/step - loss: 23.8385
Epoch 13/75
4/4 [==============================] - 0s 2ms/ste