In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [24]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)
  for l in range(1,L):
    parameters['W'+str(l)]=np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b'+str(l)]=np.zeros((layer_dims[l],1))
  return parameters

In [26]:
initialize_parameters([2,2,1])

In [5]:
def linear_forward(A_prev, W, b):
  Z=np.dot(W.T, A_prev)+b
  return Z

In [6]:
def L_layer_forward(X, parameters):
  A=X
  L=len(parameters)//2
  print(L, parameters)
  for l in range(1,L+1):
    A_prev=A
    wl=parameters['W'+str(l)]
    bl=parameters['b'+str(l)]
    A=linear_forward(A_prev, wl,bl)
  return A, A_prev

In [7]:
x=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]
para=initialize_parameters([2,2,1])
L_layer_forward(x,para)

2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [8]:
y_hat,A1=L_layer_forward(x,para)

2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


In [9]:
y_hat=y_hat[0][0]

In [10]:
A1

array([[1.6],
       [1.6]])

In [15]:
def update_parameter(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0]=parameters['W2'][0][0]+(0.001*2*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [17]:
x=df[['cgpa','profile_score']].values[0].reshape(2,1)
y=df[['lpa']].values[0][0]

parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(x,parameters)
y_hat=y_hat[0][0]

update_parameter(parameters,y,y_hat,A1,x)
parameters

2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [18]:
x=df[['cgpa','profile_score']].values[1].reshape(2,1)
y=df[['lpa']].values[1][0]

parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(x,parameters)
y_hat=y_hat[0][0]

update_parameter(parameters,y,y_hat,A1,x)
parameters

2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


{'W1': array([[0.10753323, 0.10968558],
        [0.10753323, 0.10968558]]),
 'b1': array([[0.00107618],
        [0.00107618]]),
 'W2': array([[0.114976],
        [0.114976]]),
 'b2': array([[0.124336]])}

In [19]:
x=df[['cgpa','profile_score']].values[2].reshape(2,1)
y=df[['lpa']].values[2][0]

parameters=initialize_parameters([2,2,1])
y_hat,A1=L_layer_forward(x,parameters)
y_hat=y_hat[0][0]

update_parameter(parameters,y,y_hat,A1,x)
parameters

2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}


{'W1': array([[0.10805488, 0.11342479],
        [0.10805488, 0.11342479]]),
 'b1': array([[0.00134248],
        [0.00134248]]),
 'W2': array([[0.118176],
        [0.118176]]),
 'b2': array([[0.129536]])}

In [23]:
#epoch implementation
parameters=initialize_parameters([2,2,1])
epochs=5
for i in range(epochs):
  Loss=[]
  for j in range(df.shape[0]):
    x=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['lpa']].values[j][0]
    y_hat,A1=L_layer_forward(x,parameters)
    y_hat=y_hat[0][0]
    update_parameter(parameters,y,y_hat,A1,x)
    Loss.append((y-y_hat)**2)
  print('Epoch: ',i+1, 'Loss: ', np.array(Loss).mean())

parameters


2 {'W1': array([[0.1, 0.1],
       [0.1, 0.1]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[0.1],
       [0.1]]), 'b2': array([[0.]])}
2 {'W1': array([[0.10658137, 0.10658137],
       [0.10658137, 0.10658137]]), 'b1': array([[0.00082267],
       [0.00082267]]), 'W2': array([[0.111776],
       [0.111776]]), 'b2': array([[0.119136]])}
2 {'W1': array([[0.11458955, 0.1168776 ],
       [0.11458955, 0.1168776 ]]), 'b1': array([[0.0019667],
       [0.0019667]]), 'W2': array([[0.12712927],
       [0.12712927]]), 'b2': array([[0.13612818]])}
2 {'W1': array([[0.12409711, 0.13272353],
       [0.12412266, 0.13276611]]), 'b1': array([[0.00355129],
       [0.00355555]]), 'W2': array([[0.14692424],
       [0.14731907]]), 'b2': array([[0.15810417]])}
Epoch:  1 Loss:  25.321744156025517
2 {'W1': array([[0.13482804, 0.15847776],
       [0.1349909 , 0.15884991]]), 'b1': array([[0.00569748],
       [0.0057292 ]]), 'W2': array([[0.17312488],
       [0.17534027]]), 'b2': array([[0.18773702]])}
2 {'W1':

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}