In [6]:
faqs="""
Meet Pranjal, a captivating blend of grace and charisma. At 21, she exudes a magnetic
energy that draws people in effortlessly. With an air of independence, Pranjal navigates
life with an inspiring confidence, her every step a testament to her unwavering determination.
Her beautiful locks cascade like a waterfall of silk, framing a smile that lights up the darkest of rooms.
But it's not just her outer beauty that captivates; it's her inner radiance that truly shines.
Pranjal possesses a rare maturity and understanding far beyond her years, offering wisdom
and guidance with a gentle touch. Her dedication to hard work is unparalleled, yet she always
finds time to spread joy and uplift those around her. Whether lending a listening ear or offering
sage advice, Pranjal is a beacon of positivity and encouragement. In her presence, one can't help but
feel inspired to reach for the stars.
Pranjal's pursuit of excellence extends beyond her personal achievements; she's a shining
star in academia, a beacon of inspiration for both parents and teachers alike. Her dedication
to her studies is unwavering, earning her the admiration and pride of those who know her best.
While her circle of friends may be small, it's filled with genuine connections forged through trust and
loyalty. Pranjal values quality over quantity, cherishing the true friendships that enrich her life.
In the eyes of many, she epitomizes perfection, a testament to her remarkable blend of
intelligence, compassion, and integrity. Pranjal isn't just the perfect girl in my view;
she's a rare gem in a world craving authenticity and sincerity."""

In [7]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [8]:
tokenizer=Tokenizer()

In [9]:
tokenizer.fit_on_texts([faqs])

In [10]:
tokenizer.word_index

{'her': 1,
 'a': 2,
 'of': 3,
 'and': 4,
 'pranjal': 5,
 'in': 6,
 'to': 7,
 'the': 8,
 'that': 9,
 'with': 10,
 'she': 11,
 "it's": 12,
 'is': 13,
 'blend': 14,
 'an': 15,
 'life': 16,
 'testament': 17,
 'unwavering': 18,
 'but': 19,
 'just': 20,
 'rare': 21,
 'beyond': 22,
 'offering': 23,
 'dedication': 24,
 'those': 25,
 'beacon': 26,
 'for': 27,
 "she's": 28,
 'meet': 29,
 'captivating': 30,
 'grace': 31,
 'charisma': 32,
 'at': 33,
 '21': 34,
 'exudes': 35,
 'magnetic': 36,
 'energy': 37,
 'draws': 38,
 'people': 39,
 'effortlessly': 40,
 'air': 41,
 'independence': 42,
 'navigates': 43,
 'inspiring': 44,
 'confidence': 45,
 'every': 46,
 'step': 47,
 'determination': 48,
 'beautiful': 49,
 'locks': 50,
 'cascade': 51,
 'like': 52,
 'waterfall': 53,
 'silk': 54,
 'framing': 55,
 'smile': 56,
 'lights': 57,
 'up': 58,
 'darkest': 59,
 'rooms': 60,
 'not': 61,
 'outer': 62,
 'beauty': 63,
 'captivates': 64,
 'inner': 65,
 'radiance': 66,
 'truly': 67,
 'shines': 68,
 'possesses': 6

In [11]:
input_sequences=[]
for sentence in faqs.split('\n'):
  # print(sentence)
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  print(tokenized_sentence)
  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

[]
[29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34, 11, 35, 2, 36]
[37, 9, 38, 39, 6, 40, 10, 15, 41, 3, 42, 5, 43]
[16, 10, 15, 44, 45, 1, 46, 47, 2, 17, 7, 1, 18, 48]
[1, 49, 50, 51, 52, 2, 53, 3, 54, 55, 2, 56, 9, 57, 58, 8, 59, 3, 60]
[19, 12, 61, 20, 1, 62, 63, 9, 64, 12, 1, 65, 66, 9, 67, 68]
[5, 69, 2, 21, 70, 4, 71, 72, 22, 1, 73, 23, 74]
[4, 75, 10, 2, 76, 77, 1, 24, 7, 78, 79, 13, 80, 81, 11, 82]
[83, 84, 7, 85, 86, 4, 87, 25, 88, 1, 89, 90, 2, 91, 92, 93, 23]
[94, 95, 5, 13, 2, 26, 3, 96, 4, 97, 6, 1, 98, 99, 100, 101, 19]
[102, 103, 7, 104, 27, 8, 105]
[106, 107, 3, 108, 109, 22, 1, 110, 111, 28, 2, 112]
[113, 6, 114, 2, 26, 3, 115, 27, 116, 117, 4, 118, 119, 1, 24]
[7, 1, 120, 13, 18, 121, 1, 8, 122, 4, 123, 3, 25, 124, 125, 1, 126]
[127, 1, 128, 3, 129, 130, 131, 132, 12, 133, 10, 134, 135, 136, 137, 138, 4]
[139, 5, 140, 141, 142, 143, 144, 8, 145, 146, 9, 147, 1, 16]
[6, 8, 148, 3, 149, 11, 150, 151, 2, 17, 7, 1, 152, 14, 3]
[153, 154, 4, 155, 5, 156, 20, 8, 157, 158, 6, 159, 1

In [12]:
input_sequences

[[29, 5],
 [29, 5, 2],
 [29, 5, 2, 30],
 [29, 5, 2, 30, 14],
 [29, 5, 2, 30, 14, 3],
 [29, 5, 2, 30, 14, 3, 31],
 [29, 5, 2, 30, 14, 3, 31, 4],
 [29, 5, 2, 30, 14, 3, 31, 4, 32],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34, 11],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34, 11, 35],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34, 11, 35, 2],
 [29, 5, 2, 30, 14, 3, 31, 4, 32, 33, 34, 11, 35, 2, 36],
 [37, 9],
 [37, 9, 38],
 [37, 9, 38, 39],
 [37, 9, 38, 39, 6],
 [37, 9, 38, 39, 6, 40],
 [37, 9, 38, 39, 6, 40, 10],
 [37, 9, 38, 39, 6, 40, 10, 15],
 [37, 9, 38, 39, 6, 40, 10, 15, 41],
 [37, 9, 38, 39, 6, 40, 10, 15, 41, 3],
 [37, 9, 38, 39, 6, 40, 10, 15, 41, 3, 42],
 [37, 9, 38, 39, 6, 40, 10, 15, 41, 3, 42, 5],
 [37, 9, 38, 39, 6, 40, 10, 15, 41, 3, 42, 5, 43],
 [16, 10],
 [16, 10, 15],
 [16, 10, 15, 44],
 [16, 10, 15, 44, 45],
 [16, 10, 15, 44, 45, 1],
 [16, 10, 15, 44, 45, 1, 46],
 [16, 10, 15, 44, 45, 1, 46, 47],
 [

As the size of above output is unequal and here we are performing supervised so we need to perform padding here

In [13]:
max_len=max([len(x) for x in input_sequences])

In [14]:
from keras.utils import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [15]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  29,   5],
       [  0,   0,   0, ...,  29,   5,   2],
       [  0,   0,   0, ...,   5,   2,  30],
       ...,
       [  0,   0,   0, ..., 162, 163, 164],
       [  0,   0,   0, ..., 163, 164,   4],
       [  0,   0,   0, ..., 164,   4, 165]], dtype=int32)

In [16]:
x=padded_input_sequences[:,:-1]

In [17]:
x

array([[  0,   0,   0, ...,   0,   0,  29],
       [  0,   0,   0, ...,   0,  29,   5],
       [  0,   0,   0, ...,  29,   5,   2],
       ...,
       [  0,   0,   0, ...,   2, 162, 163],
       [  0,   0,   0, ..., 162, 163, 164],
       [  0,   0,   0, ..., 163, 164,   4]], dtype=int32)

In [18]:
y=padded_input_sequences[:,-1]

In [19]:
y

array([  5,   2,  30,  14,   3,  31,   4,  32,  33,  34,  11,  35,   2,
        36,   9,  38,  39,   6,  40,  10,  15,  41,   3,  42,   5,  43,
        10,  15,  44,  45,   1,  46,  47,   2,  17,   7,   1,  18,  48,
        49,  50,  51,  52,   2,  53,   3,  54,  55,   2,  56,   9,  57,
        58,   8,  59,   3,  60,  12,  61,  20,   1,  62,  63,   9,  64,
        12,   1,  65,  66,   9,  67,  68,  69,   2,  21,  70,   4,  71,
        72,  22,   1,  73,  23,  74,  75,  10,   2,  76,  77,   1,  24,
         7,  78,  79,  13,  80,  81,  11,  82,  84,   7,  85,  86,   4,
        87,  25,  88,   1,  89,  90,   2,  91,  92,  93,  23,  95,   5,
        13,   2,  26,   3,  96,   4,  97,   6,   1,  98,  99, 100, 101,
        19, 103,   7, 104,  27,   8, 105, 107,   3, 108, 109,  22,   1,
       110, 111,  28,   2, 112,   6, 114,   2,  26,   3, 115,  27, 116,
       117,   4, 118, 119,   1,  24,   1, 120,  13,  18, 121,   1,   8,
       122,   4, 123,   3,  25, 124, 125,   1, 126,   1, 128,   

In [20]:
x.shape

(243, 18)

In [21]:
y.shape

(243,)

In [22]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=166)

In [23]:
y.shape

(243, 166)

In [24]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [33]:
model=Sequential()
model.add(Embedding(166,100,input_length=18))
model.add(LSTM(150))
model.add(Dense(166, activation='softmax'))

In [34]:
model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [35]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 18, 100)           16600     
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 166)               25066     
                                                                 
Total params: 192266 (751.04 KB)
Trainable params: 192266 (751.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
model.fit(x,y,epochs=90)

Epoch 1/90
8/8 [==============================] - 0s 40ms/step - loss: 0.0499 - accuracy: 1.0000
Epoch 2/90
8/8 [==============================] - 0s 44ms/step - loss: 0.0494 - accuracy: 1.0000
Epoch 3/90
8/8 [==============================] - 0s 35ms/step - loss: 0.0484 - accuracy: 1.0000
Epoch 4/90
8/8 [==============================] - 0s 38ms/step - loss: 0.0475 - accuracy: 1.0000
Epoch 5/90
8/8 [==============================] - 0s 38ms/step - loss: 0.0468 - accuracy: 1.0000
Epoch 6/90
8/8 [==============================] - 0s 36ms/step - loss: 0.0462 - accuracy: 1.0000
Epoch 7/90
8/8 [==============================] - 0s 36ms/step - loss: 0.0450 - accuracy: 1.0000
Epoch 8/90
8/8 [==============================] - 0s 36ms/step - loss: 0.0446 - accuracy: 1.0000
Epoch 9/90
8/8 [==============================] - 0s 36ms/step - loss: 0.0440 - accuracy: 1.0000
Epoch 10/90
8/8 [==============================] - 0s 37ms/step - loss: 0.0429 - accuracy: 1.0000
Epoch 11/90
8/8 [============

In [42]:
import numpy as np
import time

In [48]:
text="Her beautiful locks"
for i in range(10):
   #tokenize
   token_text=tokenizer.texts_to_sequences([text])[0]
   #padding
   padded_token_test=pad_sequences([token_text],maxlen=18,padding='pre')
   #predict
   pos=np.argmax(model.predict(padded_token_test))
   for word,index in tokenizer.word_index.items():
     if index==pos:
      text=text+" "+word
      print(text)
      time.sleep(2)

1/1 [==============================] - 0s 24ms/step
Her beautiful locks cascade
1/1 [==============================] - 0s 29ms/step
Her beautiful locks cascade like
1/1 [==============================] - 0s 30ms/step
Her beautiful locks cascade like a
1/1 [==============================] - 0s 42ms/step
Her beautiful locks cascade like a waterfall
1/1 [==============================] - 0s 25ms/step
Her beautiful locks cascade like a waterfall of
1/1 [==============================] - 0s 26ms/step
Her beautiful locks cascade like a waterfall of silk
1/1 [==============================] - 0s 28ms/step
Her beautiful locks cascade like a waterfall of silk framing
1/1 [==============================] - 0s 25ms/step
Her beautiful locks cascade like a waterfall of silk framing a
1/1 [==============================] - 0s 49ms/step
Her beautiful locks cascade like a waterfall of silk framing a smile
1/1 [==============================] - 0s 26ms/step
Her beautiful locks cascade like a waterfall 